obstacle_range: 2.5             #监测2.5m范围内的障碍物
raytrace_range: 3.0             #机器人监测自由空间的范围
# robot_radius: 0.225        #机器人半径，圆形机器人才用这个参数
footprint: [[-0.7,0.25],[0.3,0.25],[0.3,-0.25],[-0.7,-0.25]]
#机器人外壳的范围
inflation_radius: 0.45 #路径规划应与机器人保持0.4m以上的安全距离 一般要大于机器人半径
max_obstacle_height: 0.6  #这两个参数用于描述障碍物的最大高度和最小高度
min_obstacle_height: 0.0  
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
