global_costmap:
   global_frame: map #全局代价地图需要在哪个参考系下运行
   robot_base_frame: base_footprint #用来表示代价地图参考的机器人本体的坐标系
   update_frequency: 1.0 #用来决定全局地图信息更新的频率
   publish_frequency: 0 #用来设置设置代价地图发布可视化信息的频率，hz
   static_map: true  
   rolling_window: false
   resolution: 0.01  #tf变化最大延时
   map_type: costmap
