local_costmap:
   global_frame: odom   #用来表示全局代价地图需要在哪个参考系下运行
   robot_base_frame: base_footprint #用来表示代价地图可以参考的机器人本体的坐标系
   update_frequency: 3.0   #用来决定局部代价地图信息更新的频率
   publish_frequency: 1.0  #用于设置局部代价地图发布可视化信息的频率，hz
   rolling_window: true 
   width: 6.0
   height: 6.0
   resolution: 0.01
   transform_tolerance: 1.0
   static_map: true
   map_type: costmap
